### ISSUE TITLE
CreateRedactedResume() Error on nodejs

### ISSUE THREAD

**Issue by mahmoudabdelhalim** [affinda/affinda-typescript#1]
Hello,

**Now I use the node.js function sample. When called the CreateRedactedResume(), I got this error.**
https://github.com/affinda/affinda-typescript/blob/main/docs/samples_nodejs.md#uploads-a-resume-for-redacting

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)
    at write_ (_http_outgoing.js:722:11)
    at ClientRequest.write (_http_outgoing.js:687:15)
    at FormData.ondata (internal/streams/legacy.js:20:31)
    at FormData.emit (events.js:400:28)
    at FormData.CombinedStream.write (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:138:8)
    at FormData.CombinedStream._pipeNext (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:126:8)
    at FormData.CombinedStream._realGetNext (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:99:10)
    at FormData.CombinedStream._getNext (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:82:12)
    at FormData.CombinedStream.resume (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:154:10)
    at FormData.CombinedStream.pipe (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:66:8)
    at /var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1541:22
    at new Promise (<anonymous>)
    at NodeHttpClient.makeRequest (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1531:16)
    at NodeHttpClient.sendRequest (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1458:36)
    at /var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1084:32
    at Object.sendRequest (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:229:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**This is My code:**
----------------------------
fileData = {
    url: 'file url',
    identifier: 'my old identifier',
    fileName: 'filename name'
}
client.createRedactedResume(fileData).then( async (result) => {
    console.log("Returned data:");
    console.dir(result)
}).catch((err) => {
    console.log("An error occurred:");
    console.error(err);
});

**And when I try to use just URL, I got the same error.**
-----------------------------------------------------------------------------------
client.createRedactedResume({ url: 'file url' }).then( async (result) => {
    console.log("Returned data:");
    console.dir(result)
}).catch((err) => {
    console.log("An error occurred:");
    console.error(err);
});

Thanks

**Comment by mahmoudabdelhalim** [comment]
> Hello,
> 
> **Now I use the node.js function sample. When called the CreateRedactedResume(), I got this error.**
> https://github.com/affinda/affinda-typescript/blob/main/docs/samples_nodejs.md#uploads-a-resume-for-redacting
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)
> at write_ (_http_outgoing.js:722:11)
> at ClientRequest.write (_http_outgoing.js:687:15)
> at FormData.ondata (internal/streams/legacy.js:20:31)
> at FormData.emit (events.js:400:28)
> at FormData.CombinedStream.write (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:138:8)
> at FormData.CombinedStream._pipeNext (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:126:8)
> at FormData.CombinedStream._realGetNext (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:99:10)
> at FormData.CombinedStream._getNext (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:82:12)
> at FormData.CombinedStream.resume (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:154:10)
> at FormData.CombinedStream.pipe (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/combined-stream/lib/combined_stream.js:66:8)
> at /var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1541:22
> at new Promise ()
> at NodeHttpClient.makeRequest (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1531:16)
> at NodeHttpClient.sendRequest (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1458:36)
> at /var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:1084:32
> at Object.sendRequest (/var/www/html/works/jeelaidm/jeelaidm-nodejs/node_modules/@azure/core-rest-pipeline/dist/index.js:229:24) {
> code: 'ERR_INVALID_ARG_TYPE'
> }
> 
> ## **This is My code:**
> fileData = {
> url: 'file url',
> identifier: 'my old identifier',
> fileName: 'filename name'
> }
> client.createRedactedResume(fileData).then( async (result) => {
> console.log("Returned data:");
> console.dir(result)
> }).catch((err) => {
> console.log("An error occurred:");
> console.error(err);
> });
> 
> ## **And when I try to use just URL, I got the same error.**
> client.createRedactedResume({ url: 'file url' }).then( async (result) => {
> console.log("Returned data:");
> console.dir(result)
> }).catch((err) => {
> console.log("An error occurred:");
> console.error(err);
> });
> 
> Thanks

**Comment by mahmoudabdelhalim** [comment]
@cfculhane  Sorry I have been closed the issue wrong and I can't open it again!?

**Comment by cfculhane** [comment]
Thanks for the bug report, looking into this now! One thing - what version of the client library are you using?

**Comment by cfculhane** [comment]
Just confirmed the latest client works, can you try running `npm update @affinda/affinda` and trying again?

**Comment by mahmoudabdelhalim** [comment]
Hi @cfculhane,
Actually, I found the document on the official site has been changed for the last 2 days :), So I guessed it will happen some changed on the package so I updated it, Once updated it was working perfectly.

so far, I have a question I can't found it on the functions, I need to update the resume JSON for the user after created but I need to set the same identifier value for the user, But I can't found the function to update.

So, firstly I delete the resume for the user and then create it again as the same identifier to get the update on the file.
But it's a workaround to handle it, Is there any way to do it without doing it previously way?

I think that's all in my opinion and thank you for your efforts on this package. :+1:

**Comment by andrewbird2** [comment]
Hi @mahmoudabdelhalim , 
Resume objects are immutable - this means they can't be changed after being created.  Your approach works fine.  
Another way to do it would be to set the expiry_time parameter when submitting the resume.  This would automatically delete the resume data from our systems, so that when you come back in the future with an updated document, the previous one has already been deleted.
