### ISSUE TITLE
[BUG] conflicting expectations for compact flag

### ISSUE THREAD

**Issue by bot2600** [affinda/affinda-typescript#13]
**Describe the bug**
Using the newest SDK.

When passing `compact` to  createDocument, unlike wait which takes a string, the sdk expects a boolean. Passing a boolean returns an error: `Unexpected value for key compact: true. Value should be serialized to string first`

If I pass a string, I then get a different error: `options.compact with value true must be of type boolean`

So both possible options fail.

**To Reproduce**
        let affindaClient: AffindaAPI //boilerplate creds etc

        const result = await affindaClient.createDocument({
          fileName: document.name,
          file: document.stream,
          wait: 'true',
          collection: document.collection,
          //INFO: leave them for a bit for debugging and then clean them up
          expiryTime: new Date(new Date().setDate(new Date().getDate() + EXPIRY_DAYS)).toISOString(),
          compact: true
        })

**Expected behavior**
Either a string or a bool should work, whichever the SDK asks for

**Stacktrace / Screenshts**
`Unexpected value for key compact: true. Value should be serialized to string first`
`options.compact with value true must be of type boolean`

**Environment**
 - Client version: 7.3.0
 - NodeJS version v20.17.0

**Additional context**
This is happening when uploading a resume to a v3 parser collection which returns the debug model by default. The v2 parser collection returns a compact model by default.

**Comment by rockstarr-programmerr** [comment]
@bot2600 Thanks for reporting this! The issue should be resolved by the latest release 7.3.1. The flag `compact` should be passed in as a string.
